version: '3.9'
services:

  flask-blog:
    build:
      context: ./ 
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment: 
      - PRODUCTION=True
      - PORT=5000
    
