version: '3.9'
services:

  rest-api:
    image: matthewtee/django_rest_api:latest
    networks: 
      - dev-environment-network
    ports:
      - "80:80"
    env_file:
      - .env
    container_name: rest-api

  flask-blog:
    build:
      context: ./ 
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    networks: 
      - dev-environment-network
    environment: 
      - PRODUCTION=True
      - PORT=5000
    
networks: 
  dev-environment-network:
